# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '22.x'

- script: npm ci
  displayName: 'Install playwright dependencies'

- script: npx playwright install --with-deps
  displayName: 'Install PLaywright Browsers'

- script: SECRET_KEY=$(SECRET_KEY_VAL) npm run test_demo
  displayName: 'Run Tests'